Milestone2 - User Interface for Tic-Tac-Toe game in Ruby
ybadmus/Tic-Tac-Toe pull request #2
Opened 2021-02-06 20:04 UTC by ybadmus

This is the third project of Ruby, It's an introduction to the Object Oriented Concepts of the Ruby Programming Language. We built a Tic-Tac-Toe game using several concepts of OOP to understand the syntax for achieving them in Ruby.

2021-02-06 20:56 UTC, eypsrcnuygr requested changes
## Status: Changes Required :recycle: 
Hello team! Congratulations for making till here :smile: . Before moving on there are things to be done. :100: . Please address the changes that I'm mentioning below.

'In this step students are supposed to only mock the basic flow of the game. This means implementing a user interface that displays prompt for users (print/puts) and collects user input (gets.chomp). No game logic (for example checking who is a winner) is required in this milestone - instead, students can just display "The winner is X" no mater who won. Usage of inline comments in this milestone is allowed. '  This is the explanation from our guide. I've tried your game and after giving the users' names, there is just one turn that it asks for the users' movements. I'll give you the expectations as a list. Try to satisfy them one by one, please. You need to print out a board and give us some interactions, which we don't have right now.

* [ ] `[REQUIRED]` game tells which player turn it is (without computing who the winner is)
* [ ] `[REQUIRED]` game asks the player to select from available moves
* [ ] `[REQUIRED]` game informs the player if the selected move is invalid (without computing what an invalid move is)
* [ ] `[REQUIRED]` game displays board after the player move (without computing which spots on the board are taken)
* [ ] `[REQUIRED]` game informs the player if the selected move is a winning move (without computing the winning move)
* [ ] `[REQUIRED]` game informs the player if the selected move is a draw move (without computing draw)
* [ ] `[REQUIRED]` game repeats all actions for the next player's move.

To satisfy these conditions you must have a loop in your code. Also, you need to terminate it if certain conditions are met.

Thanks for adding a decent Readme and it's a good start. All you need to do fill the lib directory, as mentioned above. After making your changes, please submit for a re-review.

If you have any questions, you can reach out to me via Slack. :100: 
_Eyüp Sercan UYGUR_

2021-02-07 00:34 UTC, ebeagusamuel requested changes
# Changes Required :receipt: 
### Hey there :wave: 
###### You have done well in implementing some of the changes asked of you. There are still some cases that still need to be met before your project can be approved.
- [ ] [REQUIRED] game asks the player to select from available moves
- [ ] [REQUIRED] game informs the player if the selected move is a winning move (without computing the winning move)
- [ ] [REQUIRED] game informs the player if the selected move is a draw move (without computing draw)
#### As stated by the previous reviewer, in this milestone you only need to mock the flow of the game and not focus on writing any logic. For instance, you can just pick a particular number and if the user picks that number you can assume that the user has won the game and your game should declare that user a winner. This is just a basic mock of the game. Request another review when you are done.
slack(@ebeagusamuel)

2021-02-07 01:14 UTC, kevincappuccino requested changes
# [STATUS] CHANGES REQUESTED ♻

### Hey, nice project so far. I noticed that you are missing some key features of this project, so we have to improve a few things before moving on:

- [ ] Your project asks for players name but don't use them;
- [ ] You have typo errors when asking for players name: Player 2: Choose **_and_** nickname
- [ ] Your project isn't showing player's choice at the board;
- [ ] Your board is starting from 9 to 1, when I type 1 to mark X, it makes the 9th box empty, and so on;
Please fix that, because is impossible to play without even knowing where you're putting your symbol.
![image](https://user-images.githubusercontent.com/56762529/107133547-234e1600-68c8-11eb-95b3-2246a515fca8.png)

## As always, I wish you all the very best and see you at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

2021-02-07 02:58 UTC, GzimAsani approved these changes
> # **STATUS: APPROVED** 
> Congratulations **@ybadmus ** , Great job implementing all the changes asked from the reviewers.


<hr>
### if you have any question kindly reach me on slack @GzimAsani

### HAPPY CODING :computer:

2021-02-07 12:17 UTC, merged